<div class="list-brands">
    <h1>All the best Brands</h1>
    <ul id="owl-demo" >
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Dewalt_BW_192x125.jpg" alt="Dewalt">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Bosch_B-W_192x125.jpg" alt="Bosch">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Festool_BW_192x125.jpg" alt="Festool">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Husqvarna.jpg" alt="Husqvarna">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Milwaukee_BW_192x125.jpg" alt="Milwaukee">
            </a>
        </li>
        <!--            <div class="owl-prev">prev</div>-->
    </ul>
    <ul class="brandlist-mobile" >
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Dewalt_BW_192x125.jpg" alt="Dewalt">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Bosch_B-W_192x125.jpg" alt="Bosch">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Festool_BW_192x125.jpg" alt="Festool">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Husqvarna.jpg" alt="Husqvarna">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Cigweld_B-W_192x125.jpg" alt="Cigweld">
            </a>
        </li>
        <li class="item" >
            <a href="#" title="Cigweld">
                <img src="https://www.totaltools.com.au/media/catalog/category/Milwaukee_BW_192x125.jpg" alt="Milwaukee">
            </a>
        </li>
        <!--            <div class="owl-prev">prev</div>-->
    </ul>
</div>
